version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      cron: "0 6 */28 * *"
      timezone: "Australia/Adelaide"
    open-pull-requests-limit: 3
    allow:
      - dependency-type: "production"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      production-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    reviewers:
      - "drillvoice"
    assignees:
      - "drillvoice"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    security-updates: true

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      cron: "0 6 1 */3 *"
      timezone: "Australia/Adelaide"
    open-pull-requests-limit: 3
    allow:
      - dependency-type: "production"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    reviewers:
      - "drillvoice"
    assignees:
      - "drillvoice"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    security-updates: true

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      cron: "0 6 */28 * *"
      timezone: "Australia/Adelaide"
    open-pull-requests-limit: 3
    security-updates: true
