version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "06:00"
      timezone: "Australia/Adelaide"
    open-pull-requests-limit: 3
    allow:
      - dependency-type: "production"
    groups:
      production-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    reviewers:
      - "drillvoice"
    assignees:
      - "drillvoice"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    security-updates: true

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "06:00"
      timezone: "Australia/Adelaide"
    open-pull-requests-limit: 3
    security-updates: true
